# Generated by Django 4.1.2 on 2022-10-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="critics",
            new_name="critic",
        ),
    ]
