# Generated by Django 4.1.2 on 2022-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("duration", models.CharField(max_length=10)),
                ("premiere", models.DateField()),
                ("classification", models.IntegerField()),
                ("synopsis", models.TextField()),
            ],
        ),
    ]
