# Generated by Django 4.1.2 on 2022-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_critics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecritic",
            name="email",
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
