# Generated by Django 4.1.2 on 2022-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_critics", "0002_alter_moviecritic_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecritic",
            name="email",
            field=models.EmailField(max_length=127, unique=True),
        ),
    ]
