# Generated by Django 4.1.2 on 2022-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                (
                    "movies",
                    models.ManyToManyField(related_name="genres", to="movie.movies"),
                ),
            ],
        ),
    ]
